### ISSUE TITLE
Cover Art 

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/sense-hat-data-logger#2]
@samalderhyde I'll need some cover art for this resource soon, the resource involves kids writing code to capture data and then carrying out experiments to capture that data. The data they capture is up to them and the more interesting the scenario the better.

We could include some examples of capturing data on the cover, such as free-fall, putting a pi in the oven/fridge, HAB flight.

**Comment by samalderhyde** [comment]
Ok great, I'll work on a rough design asap. Would this eventually be part of the Astro Pi themed resources or more of a real world Sense HAT activity?

**Comment by jrobinson-uk** [comment]
I would imagine both. cover art should be real world themed but add an Astro Pi mission badge?

**Comment by samalderhyde** [comment]
Ok cool
