### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/sense-hat-data-logger#3]
@LornaLynch There's a couple of peripheral sheets that I'll add later but this is ready for copy please.

**Comment by LornaLynch** [comment]
Thanks: I'll get on it.

**Comment by LornaLynch** [comment]
Just noticed that, in Code, one of the python files has a tilde after it (~): I assume it shouldn't be there, but wanted to check.

**Comment by bennuttall** [comment]
That's an autosave file. @jrobinson-uk obviously ran `git commit -am` without a care in the world.

It should be deleted.

**Comment by jrobinson-uk** [comment]
Haven't got time to care

**Comment by bennuttall** [comment]
https://github.com/raspberrypilearning/sense-hat-data-logger/commit/7147319bb2e0374e472bf0865b87c0bcd3a9a3ad

See.

**Comment by LornaLynch** [comment]
Good stuff: I'll delete it. Just didn't want to accidentally muck something up (I remember my 'changing the URL' debacle)

**Comment by LornaLynch** [comment]
OK: I think I'm done. I've added in the links to the Sensing Space activity, which were missing. I hope everything's ok!
