### ISSUE TITLE
Worksheet promises info that's missing

### ISSUE THREAD

**Issue by helenlynn** [raspberrypilearning/sense-hat-data-logger#6]
Introduction to [Worksheet2](https://github.com/raspberrypilearning/sense-hat-data-logger/blob/master/worksheet2.md) promises "Being able to start and stop logging using the Sense HAT joystick", but this section isn't present in the worksheet.

**Comment by lawsie** [comment]
Haha, I think @jrobinson-uk just removed the reference to the joystick! Closing the issue.
